### ISSUE TITLE
데이터가 너무 커서 push가 되지 않는다...

### ISSUE THREAD

**Issue by ggjae** [ggjae/unreal-play#3]
![image](https://user-images.githubusercontent.com/22047551/119095599-6f732f80-ba4d-11eb-97af-5c6e0586ff64.png)
ㅠㅠ...

**Comment by wogns0197** [comment]
check this : https://newsight.tistory.com/330

**Comment by ggjae** [comment]
감사합니다 형님 ㅎㅎㅎ
